### ISSUE TITLE
Pretrained weights & training time 

### ISSUE THREAD

**Issue by ariel415el** [moritztng/stylegan2-pytorch#1]
Hi,
Can you upload the trained weights you used to generate the README images.
Also how much time did it take to train on FFHQ-128

I'm traying to adapt your code and train on a 64x64 or 32x32 FFHQ versions
Thanks for the help.

**Comment by moritztng** [comment]
Hey, there is a link to the [trained weights](https://drive.google.com/file/d/1aqB2SNG6WaQJU6glyN0FsThP8nF1YT-a/view?usp=sharing) in the README. It took 9 epochs and that was a few days I guess. Good luck and I hope I could help you!
